[app]
name = "fastapi-admin"
env = "dev"
host = "127.0.0.1"
port = 8003

[secret]
secret_key = "your-secret-key"
algorithm = "HS256"
access_token_expires = 60

[database]
user = "root"
password = "123456"
host = "localhost"
port = 3306
database = "fastapi_admin"
echo = true # 线下环境设置成true，线上环境改为false
pool_size = 10
max_overflow = 20
pool_timeout = 30
pool_recycle = 1800

[redis]
host = "localhost"
port = 6379
db = 0

[opentelemetry]
otel_exporter_endpoint="http://localhost:4317"

[logging]
dir = "logs"
level = "INFO"
max_bytes = "50MB" # 如10KB / 50MB / 1GB
backup_count = 30 # 保留最近30个日志文件
